FROM node:20

COPY ./api/docker/sources.list /etc/apt/sources.list

RUN apt-get update \
    && apt-get install -y sudo mycli less tzdata \
    && npm install -g typescript ts-node \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV TZ Europe/Paris

ENV SHELL /bin/bash

WORKDIR /home/api

CMD ["/bin/bash"]
